/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monitoringbb;

import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import koneksi.koneksiDB;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import monitoringbb.grafikPemakaian;


/**
 *
 * @author ADMIN-PC
 */
public class MainMenu extends javax.swing.JFrame {
    
    int GlobalHarga;
    int waktumulai=0;
    

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        datatable();
        comBB();
        datatableKendaraan();
        lisKendaraan();
        datatablePemakaian();
        jam();
        tanggal();
               
    }
    
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        inFramePemakaian = new javax.swing.JInternalFrame();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtNplatP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtJenisP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTahunP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtKMawal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pemakaianBB = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        pemakaianHargaBB = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        pemakaianKMbb = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        totalBiaya = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtKMakhir = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtJarakT = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listKendaraan = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        btnPsiman = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPemakaian = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        lihatGrafik = new javax.swing.JButton();
        inFrameKendaraan = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        tKendaraan = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNoPlat = new javax.swing.JTextField();
        txtJenisKen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTahun = new javax.swing.JTextField();
        comBB = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        KMliter = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnTambahKen = new javax.swing.JButton();
        btnSimpanKen = new javax.swing.JButton();
        btnPerbaharuiKen = new javax.swing.JButton();
        btnHapusKen = new javax.swing.JButton();
        inFrameBB = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        tBB = new javax.swing.JTable();
        btnTambahBB = new javax.swing.JButton();
        btnSimpanBB = new javax.swing.JButton();
        btnHapusBB = new javax.swing.JButton();
        btnPerbaharuiBB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtIDbb = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNamaBb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txtJam = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Monitoring Bahan Bakar Kendaraan");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(80, 20));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(45, 69, 242));
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Sistem Monitoring Bahan Bakar");

        jTabbedPane2.setName("Sistem monitoring Bahan Bakar Kendaraan"); // NOI18N

        inFramePemakaian.setBackground(new java.awt.Color(255, 255, 255));
        inFramePemakaian.setClosable(true);
        inFramePemakaian.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        inFramePemakaian.setResizable(true);
        inFramePemakaian.setVisible(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setPreferredSize(new java.awt.Dimension(930, 133));

        jLabel14.setText("NO Plat");

        txtNplatP.setEditable(false);

        jLabel9.setText("Jenis");

        txtJenisP.setEditable(false);

        jLabel10.setText("Tahun");

        txtTahunP.setEditable(false);

        jLabel11.setText("KM Awal");

        jLabel16.setText("Bahan Bakar");

        pemakaianBB.setEditable(false);

        jLabel19.setText("Harga");

        pemakaianHargaBB.setEditable(false);

        jLabel17.setText("KM/Liter");

        pemakaianKMbb.setEditable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        totalBiaya.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalBiaya.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalBiaya, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalBiaya, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Biaya Perjalanan :");

        jLabel13.setText("KM Akhir");

        jLabel12.setText("Jarak Tempuh");

        txtJarakT.setEditable(false);

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNplatP, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisP, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTahunP, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pemakaianHargaBB, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pemakaianBB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKMawal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pemakaianKMbb, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtKMakhir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtJarakT, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHitung))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtKMawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKMakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtJarakT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(btnHitung))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pemakaianBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pemakaianHargaBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNplatP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJenisP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTahunP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pemakaianKMbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setText("NO Plat :");

        listKendaraan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listKendaraan.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listKendaraanValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listKendaraan);

        jButton1.setText("Tambah");

        btnPsiman.setText("Simpan");
        btnPsiman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPsimanActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");

        tPemakaian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tPemakaian.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tPemakaian);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lihatGrafik.setText("Lihat Grafik");
        lihatGrafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatGrafikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lihatGrafik)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPsiman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(528, 528, 528)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPsiman)
                                .addComponent(jButton1)
                                .addComponent(jButton3))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lihatGrafik)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout inFramePemakaianLayout = new javax.swing.GroupLayout(inFramePemakaian.getContentPane());
        inFramePemakaian.getContentPane().setLayout(inFramePemakaianLayout);
        inFramePemakaianLayout.setHorizontalGroup(
            inFramePemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inFramePemakaianLayout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(765, 765, 765)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addGap(879, 879, 879))
            .addGroup(inFramePemakaianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inFramePemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inFramePemakaianLayout.setVerticalGroup(
            inFramePemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(inFramePemakaianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Pemakaian", inFramePemakaian);

        inFrameKendaraan.setTitle("Data Kendaraan");
        inFrameKendaraan.setVisible(true);

        tKendaraan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tKendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tKendaraanMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tKendaraan);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("NO Plat");

        txtNoPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoPlatActionPerformed(evt);
            }
        });

        jLabel6.setText("Jenis Kendaraan");

        jLabel7.setText("Tahun");

        comBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBBActionPerformed(evt);
            }
        });

        jLabel8.setText("Bahan Bakar");

        jLabel18.setText("KM/Liter");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNoPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comBB, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KMliter, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisKen, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNoPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtJenisKen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KMliter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnTambahKen.setText("Tambah");
        btnTambahKen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKenActionPerformed(evt);
            }
        });

        btnSimpanKen.setText("Simpan");
        btnSimpanKen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanKenActionPerformed(evt);
            }
        });

        btnPerbaharuiKen.setText("Perbaharui");

        btnHapusKen.setText("Hapus");
        btnHapusKen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnTambahKen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpanKen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPerbaharuiKen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapusKen)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahKen)
                    .addComponent(btnSimpanKen)
                    .addComponent(btnHapusKen)
                    .addComponent(btnPerbaharuiKen))
                .addContainerGap())
        );

        javax.swing.GroupLayout inFrameKendaraanLayout = new javax.swing.GroupLayout(inFrameKendaraan.getContentPane());
        inFrameKendaraan.getContentPane().setLayout(inFrameKendaraanLayout);
        inFrameKendaraanLayout.setHorizontalGroup(
            inFrameKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inFrameKendaraanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inFrameKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        inFrameKendaraanLayout.setVerticalGroup(
            inFrameKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inFrameKendaraanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inFrameKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inFrameKendaraanLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Kendaraan", inFrameKendaraan);

        inFrameBB.setTitle("BAHAN BAKAR");
        inFrameBB.setVisible(true);

        tBB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tBB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tBB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tBBMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tBB);

        btnTambahBB.setText("Tambah");
        btnTambahBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBBActionPerformed(evt);
            }
        });

        btnSimpanBB.setText("Simpan");
        btnSimpanBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanBBActionPerformed(evt);
            }
        });

        btnHapusBB.setText("Hapus");
        btnHapusBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusBBActionPerformed(evt);
            }
        });

        btnPerbaharuiBB.setText("Perbaharui");
        btnPerbaharuiBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerbaharuiBBActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 102, 255), new java.awt.Color(153, 153, 153)));

        jLabel2.setText("ID");

        jLabel3.setText("Nama");

        jLabel4.setText("Harga");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtIDbb, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaBb, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaBb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout inFrameBBLayout = new javax.swing.GroupLayout(inFrameBB.getContentPane());
        inFrameBB.getContentPane().setLayout(inFrameBBLayout);
        inFrameBBLayout.setHorizontalGroup(
            inFrameBBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inFrameBBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inFrameBBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inFrameBBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inFrameBBLayout.createSequentialGroup()
                            .addComponent(btnTambahBB)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSimpanBB)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPerbaharuiBB)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnHapusBB))))
                .addContainerGap(500, Short.MAX_VALUE))
        );
        inFrameBBLayout.setVerticalGroup(
            inFrameBBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inFrameBBLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inFrameBBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahBB)
                    .addComponent(btnSimpanBB)
                    .addComponent(btnHapusBB)
                    .addComponent(btnPerbaharuiBB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Bahan Bakar", inFrameBB);

        jPanel7.setBackground(new java.awt.Color(40, 200, 50));

        txtJam.setFont(new java.awt.Font("Lucida Console", 1, 19)); // NOI18N
        txtJam.setForeground(new java.awt.Color(255, 255, 255));
        txtJam.setText("JAM");

        txtTanggal.setForeground(new java.awt.Color(255, 255, 255));
        txtTanggal.setText("Tanggal");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addComponent(txtTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtTanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtJam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        label1.getAccessibleContext().setAccessibleName("JudulForm");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void jam(){
        new Thread(){
            @Override
            public void run(){
                while(waktumulai == 0){
                    Calendar kalender = new GregorianCalendar();
                    int jam = kalender.get(Calendar.HOUR);
                    int menit = kalender.get(Calendar.MINUTE);
                    int detik = kalender.get(Calendar.SECOND);
                    int AM_PM = kalender.get(Calendar.AM_PM);
                    int tanggal = kalender.get(Calendar.DATE);
                    
                    
                    String Siang_Malam;
                    if (AM_PM == 1){
                        Siang_Malam="PM";
                    }else{
                        Siang_Malam ="AM";
                    }
                    String time = jam + ":" + menit + ":" + detik + " " + Siang_Malam;
                    //String tanggal2 = "Sampit, Tanggal : " + tanggal + "  Bulan :" + bulan;
                    txtJam.setText(time);
                    //tempatTanggal.setText(tanggal2);
               }
            }
        }.start();
    }
    
    // Menampilkan Tanggal Saat ini
    public void tanggal(){
        Date tanggal = new Date();
        SimpleDateFormat formatTangaalSederhana = new SimpleDateFormat("dd MMMM yyyy - HH:mm:ss");
        
        String tgl = formatTangaalSederhana.format(tanggal);
        txtTanggal.setText(tgl);
    }
    
    private void btnTambahBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBBActionPerformed
        // TODO add your handling code here:
        txtIDbb.setText("");
        txtNamaBb.setText("");
        txtHarga.setText("");
    }//GEN-LAST:event_btnTambahBBActionPerformed

    private void btnSimpanBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanBBActionPerformed
        // TODO add your handling code here:
        String id_BB = txtIDbb.getText();
        String nama_BB = txtNamaBb.getText();
        String harga = txtHarga.getText();
        
        try {
            Statement statement = (Statement) koneksiDB.GetConnection() .createStatement();
            statement.executeUpdate("insert into t_bb VALUES ('" + id_BB + "','" + nama_BB +"','"+ harga +"');");
            statement.close();
            
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        }catch (Exception t){
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        }        
        datatable();
    }//GEN-LAST:event_btnSimpanBBActionPerformed

    /*
     * Coding Tab Kendaraan
     */
    
    public void datatableKendaraan(){
        DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("No Plat");
        tbl.addColumn("Jenis");
        tbl.addColumn("Tahun");
        tbl.addColumn("Bahan Bakar");
        tbl.addColumn("KM/Liter");
        tKendaraan.setModel(tbl);
        try{
            Statement statement= (Statement) koneksiDB.GetConnection() .createStatement();
            ResultSet res=statement.executeQuery("SELECT a.No_Plat, a.Jenis, a.Tahun, b.nama_BB, a.literKM\n" +
                                                 "FROM t_kendaraan as a \n" +
                                                 "Join t_BB as b\n" +
                                                 "WHERE b.id_bb=a.id_BB Order by a.Jenis");
                        
            while (res.next())
                
            {
                tbl.addRow(new Object[]{
                    res.getString ("No_Plat"),
                    res.getString ("Jenis"),
                    res.getString ("Tahun"),
                    res.getString ("nama_BB"),
                    res.getString ("literKM")
            });
                tKendaraan.setModel(tbl);
        }
    }catch (Exception e){
        JOptionPane.showMessageDialog(rootPane, "tabel Bahan Bakar Tidak Ditemukan");
        }
    }
    
    private void btnTambahKenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKenActionPerformed
        // TODO add your handling code here:
        txtNoPlat.setText("");
        txtJenisKen.setText("");
        txtTahun.setText("");
        KMliter.setText("");
    }//GEN-LAST:event_btnTambahKenActionPerformed
    
    private void btnSimpanKenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanKenActionPerformed
        // TODO add your handling code here:
        String No_Plat = txtNoPlat.getText();
        String Jenis = txtJenisKen.getText();
        String Tahun = txtTahun.getText();
        String BB = (String) comBB.getSelectedItem();
        String id_BB = BB.substring(0, 4);
        String literKM = KMliter.getText();
        
        try {
            Statement statement = (Statement) koneksiDB.GetConnection() .createStatement();
            statement.executeUpdate("insert into t_kendaraan VALUES ('" + No_Plat + "','"+ Jenis +"','" + Tahun +"','"+ id_BB +"','"+ literKM +"');");
            statement.close();
           
            JOptionPane.showMessageDialog(null, "Data kendaraan berhasil disimpan");
        }catch (Exception t){
            JOptionPane.showMessageDialog(null, "Data kendaraan gagal disimpan");
        }        
        datatableKendaraan();
    }//GEN-LAST:event_btnSimpanKenActionPerformed

    
    
    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:

        int a = Integer.valueOf(txtKMakhir.getText());
        int b = Integer.valueOf(txtKMawal.getText());
        int j = Integer.valueOf(pemakaianKMbb.getText());

        int c = a-b;
        String d = Integer.toString(c);
        txtJarakT.setText(d);

        int f = c/j * GlobalHarga;
        String g = Integer.toString(f);
        totalBiaya.setText("Rp. " + g);

        /*
        String kmAwal = txtKMawal.getText();
        if (kmAwal == null) {
            String kmAkhir = txtKMakhir.getText();
            txtJarakT.setText(kmAkhir);
            //int k = Integer.valueOf(txtKMakhir.getText());
            //int l = (k/j)*GlobalHarga;
            //totalBiaya.setText("Rp. " + l);
        } else {
            int c = a-b;
            String d = Integer.toString(c);
            txtJarakT.setText(d);

            int f = c/j * GlobalHarga;
            String g = Integer.toString(f);
            totalBiaya.setText("Rp. " + g);
        }
        */

    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnPsimanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPsimanActionPerformed
        // TODO add your handling code here:
        String No_Plat = txtNplatP.getText();
        String KM_Awal = txtKMakhir.getText();
        String Jarak_Tempuh = txtJarakT.getText();
        String Biaya_Perjalanan = totalBiaya.getText();

        try {
            Statement statement = (Statement) koneksiDB.GetConnection() .createStatement();
            statement.executeUpdate("insert into t_pemakaian (No_Plat,KM_Awal,Jarak_Tempuh,Biaya_Perjalanan) VALUES ('" + No_Plat +"','" + KM_Awal +"','"+ Jarak_Tempuh +"','"+ Biaya_Perjalanan +"');");
            statement.close();
            
            JOptionPane.showMessageDialog(null, "Data kendaraan berhasil disimpan");
        }catch (Exception t){
            JOptionPane.showMessageDialog(null, "Data kendaraan gagal disimpan");
        }
        datatablePemakaian();

    }//GEN-LAST:event_btnPsimanActionPerformed

    private void listKendaraanValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listKendaraanValueChanged
        // TODO add your handling code here:

        txtKMakhir.setText("");
        Object[] selectedItems = listKendaraan.getSelectedValues();
        StringBuffer No_Plat = new StringBuffer();
        for (Object item : selectedItems) {
            No_Plat.append(item.toString());
        }

        try{
            Statement statement= (Statement) koneksiDB.GetConnection() .createStatement();
            ResultSet res2=statement.executeQuery("SELECT a.No_Plat, a.Jenis, a.Tahun, a.literKM, b.id_BB, b.nama_BB, b.harga\n" +
                "FROM t_kendaraan as a\n" +
                "JOIN t_bb as b\n" +
                "WHERE b.id_BB=a.id_BB AND No_Plat='"+ No_Plat +"'");
                        
            while (res2.next())
            {
                String nama_BB = res2.getString("nama_BB");
                String harga = res2.getString("harga");
                String literKM = res2.getString("literKM");
                String NO_Plat = res2.getString("No_Plat");
                String Jenis = res2.getString ("Jenis");
                String Tahun = res2.getString ("Tahun");

                txtNplatP.setText(NO_Plat);
                txtJenisP.setText(Jenis);
                txtTahunP.setText(Tahun);
                pemakaianBB.setText(nama_BB);
                pemakaianKMbb.setText(literKM);
                pemakaianHargaBB.setText(harga);

            }
            ResultSet res=statement.executeQuery(
                "SELECT a.No_Plat, a.Jenis, a.Tahun, "
                + "c.nama_BB, c.harga, b.KM_Awal, b.Jarak_Tempuh "
                + "FROM t_pemakaian as b "
                + "JOIN t_kendaraan as a "
                + "JOIN t_bb as c "
                + "WHERE c.id_BB=a.id_BB AND a.No_Plat=b.No_Plat AND b.No_Plat='"+ No_Plat +"'");
            while (res.next())
            {
                String strHarga = res.getString("harga");
                int Harga = Integer.valueOf(strHarga);
                this.GlobalHarga = Harga;

                String KM_Awal = res.getString("KM_Awal");

                if (KM_Awal.isEmpty()) {
                    txtKMawal.setText("");
                }else{
                    txtKMawal.setText(KM_Awal);
                }
            }

        }catch (Exception a){
            JOptionPane.showMessageDialog(null, "Data Kendaraan di List Tidak Dapat ditampilakan!");
        }

        DefaultTableModel tbl= new DefaultTableModel();
        tbl.addColumn("ID");
        tbl.addColumn("NO Plat");
        tbl.addColumn("Jenis");
        //tbl.addColumn("Tahun");
        tbl.addColumn("Bahan Bakar");
        //tbl.addColumn("KM/Liter");
        //tbl.addColumn("Harga");
        tbl.addColumn("KM Awal");
        tbl.addColumn("Jarak Tempuh");
        tbl.addColumn("Biaya Perjalanan");
        tPemakaian.setModel(tbl);
        try{
            Statement statement= (Statement) koneksiDB.GetConnection() .createStatement();
            ResultSet res=statement.executeQuery("SELECT b.id_Pemakaian, a.No_Plat, a.Jenis, "
                + "c.nama_BB, b.KM_Awal, b.Jarak_Tempuh, b.Biaya_Perjalanan "
                + "FROM t_pemakaian as b "
                + "JOIN t_kendaraan as a JOIN t_bb as c "
                + "WHERE c.id_BB=a.id_BB AND a.No_Plat=b.No_Plat AND b.No_Plat='"+ No_Plat +"'");
           
            while (res.next())
            {
                tbl.addRow(new Object[]{
                    res.getString ("id_Pemakaian"),
                    res.getString ("No_Plat"),
                    res.getString ("Jenis"),
                    //res.getString ("Tahun"),
                    res.getString ("nama_BB"),
                    //res.getString ("literKM"),
                    //res.getString ("harga"),
                    res.getString ("KM_Awal"),
                    res.getString ("Jarak_Tempuh"),
                    res.getString ("Biaya_Perjalanan"),
                });
                tPemakaian.setModel(tbl);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data kendaraan dipemakaian tidak dapat dilihat","Error Dialog", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_listKendaraanValueChanged

    private void btnHapusKenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKenActionPerformed
        // TODO add your handling code here:
        String No_Plat = txtNoPlat.getText();

        try {
            Statement statement = (Statement) koneksiDB.GetConnection() .createStatement();
            statement.executeUpdate("DELETE from t_kendaraan where No_Plat=('" + No_Plat + "');");
            JOptionPane.showMessageDialog(null, "Data berhasil di Hapus");
            statement.close();
            

        }catch (Exception u){
            JOptionPane.showMessageDialog(null, "Data gagal di HAPUSS");
        }
        datatableKendaraan();

    }//GEN-LAST:event_btnHapusKenActionPerformed

    private void btnHapusBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusBBActionPerformed
        // TODO add your handling code here:
        String id_BB = txtIDbb.getText();

        try {
            Statement statement = (Statement) koneksiDB.GetConnection() .createStatement();
            statement.executeUpdate("DELETE from t_bb where id_BB=('" + id_BB + "');");
            JOptionPane.showMessageDialog(null, "Data berhasil di Hapus");
            statement.close();
            
        }catch (Exception u){
            JOptionPane.showMessageDialog(null, "Data gagal di HAPUSS");
        }
        datatable();
    }//GEN-LAST:event_btnHapusBBActionPerformed

    private void btnPerbaharuiBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerbaharuiBBActionPerformed
        // TODO add your handling code here:
        int kolom =0;
        int baris = tBB.getSelectedRow();
        String id_BB = tBB.getModel().getValueAt(baris, kolom).toString();
        String nama_BB = txtNamaBb.getText();
        String harga = txtHarga.getText();
        
        txtIDbb.setText(id_BB);

        try {
            Statement statement = (Statement) koneksiDB.GetConnection() .createStatement();
            statement.executeUpdate("Update t_bb SET nama_BB='"+ nama_BB +"', harga='"+ harga +"'"
                                  + "where id_BB=('" + id_BB + "');");
            JOptionPane.showMessageDialog(null, "Data berhasil di Perbaharui");
            statement.close();
            
        }catch (Exception u){
            JOptionPane.showMessageDialog(null, "Data gagal di HAPUSS");
        }
        datatable();
        
    }//GEN-LAST:event_btnPerbaharuiBBActionPerformed

    private void tBBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tBBMouseClicked
        // TODO add your handling code here:
        int kolom =0;
        int baris = tBB.getSelectedRow();
        String id_BB = tBB.getModel().getValueAt(baris, kolom).toString();
        String nama_BB = tBB.getModel().getValueAt(baris, 1).toString();
        String harga = tBB.getModel().getValueAt(baris, 2).toString();
       
        txtIDbb.setText(id_BB);
        txtNamaBb.setText(nama_BB);
        txtHarga.setText(harga);
    }//GEN-LAST:event_tBBMouseClicked

    private void tKendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tKendaraanMouseClicked
        // TODO add your handling code here:
        int kolom =0;
        int baris = tKendaraan.getSelectedRow();
        String No_Plat = tKendaraan.getModel().getValueAt(baris, kolom).toString();
        String Jenis = tKendaraan.getModel().getValueAt(baris, 1).toString();
        String Tahun = tKendaraan.getModel().getValueAt(baris, 2).toString();
        String KMLiter = tKendaraan.getModel().getValueAt(baris, 4).toString();
       
        txtNoPlat.setText(No_Plat);
        txtJenisKen.setText(Jenis);
        txtTahun.setText(Tahun);
        KMliter.setText(KMLiter);
        
    }//GEN-LAST:event_tKendaraanMouseClicked

    private void txtNoPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoPlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPlatActionPerformed

    private void lihatGrafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatGrafikActionPerformed
        // TODO add your handling code here:
      
        grafikPemakaian gPemakaiaan1=new grafikPemakaian();
        gPemakaiaan1.gPemakaiaan();
    }//GEN-LAST:event_lihatGrafikActionPerformed

    private void comBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBBActionPerformed

    
    
    
        
    
    
    /*
     * Coding CombBox Bahan Bakar di Tab Kendaraan
     */
    
    public void comBB(){    
            try{
                Statement statement= (Statement) koneksiDB.GetConnection() .createStatement();
                ResultSet res=statement.executeQuery("select * from t_bb");
                while (res.next())
                {
                    String id_BB = res.getString("id_BB");
                    String nama_BB = res.getString("nama_BB");

                    comBB.addItem(id_BB +": "+ nama_BB);
                }

            }catch (Exception a){
                JOptionPane.showMessageDialog(null, "Data bahan Bakar di Combobox Tidak Dapat di tampilakan!");
            }    
    }
    
    public void datatablePemakaian(){
        DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("ID");
        tbl.addColumn("NO Plat");
        tbl.addColumn("Jenis");
        //tbl.addColumn("Tahun");
        tbl.addColumn("Bahan Bakar");
        //tbl.addColumn("KM/Liter");
        //tbl.addColumn("Harga");
        tbl.addColumn("KM Awal");
        tbl.addColumn("Jarak Tempuh");
        tbl.addColumn("Biaya Perjalanan");
        tPemakaian.setModel(tbl);
        try{
            Statement statement= (Statement) koneksiDB.GetConnection() .createStatement();
            ResultSet res=statement.executeQuery("SELECT b.id_Pemakaian, a.No_Plat, a.Jenis, "
                    + "c.nama_BB, b.KM_Awal, b.Jarak_Tempuh, b.Biaya_Perjalanan "
                    + "FROM t_pemakaian as b JOIN t_kendaraan as a "
                    + "JOIN t_bb as c "
                    + "WHERE c.id_BB=a.id_BB AND a.No_Plat=b.No_Plat");
            while (res.next())
            {
                tbl.addRow(new Object[]{
                    res.getString ("id_Pemakaian"),
                    res.getString ("No_Plat"),
                    res.getString ("Jenis"),
                    //res.getString ("Tahun"),
                    res.getString ("nama_BB"),
                    //res.getString ("literKM"),
                    //res.getString ("harga"),
                    res.getString ("KM_Awal"),
                    res.getString ("Jarak_Tempuh"),
                    res.getString ("Biaya_Perjalanan"),
            });
                tPemakaian.setModel(tbl);
        }
    }catch (Exception e){
        JOptionPane.showMessageDialog(rootPane, "tabel Bahan Bakar Tidak Ditemukan");
        }
    }
    
    /*
     * Coding List Box di Tab Pemekaian
     */
    
    public void lisKendaraan(){
        DefaultListModel model = new DefaultListModel();
        
            try{
                Statement statement= (Statement) koneksiDB.GetConnection() .createStatement();
                ResultSet res=statement.executeQuery("select * from t_kendaraan");
                while (res.next())
                                        
                {
                    String NO_Plat = res.getString("No_Plat");
                                        
                    model.addElement(NO_Plat);

                    listKendaraan.setModel(model);
                }
                

            }catch (Exception a){
                JOptionPane.showMessageDialog(null, "Data Kendaraan di List Tidak Dapat ditampilakan!");
            }    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    
    /*
     * Tabel Bahan Bakar
     */
    public void datatable(){
        DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("ID");
        tbl.addColumn("Jenis");
        tbl.addColumn("Harga");
        tBB.setModel(tbl);
        try{
            Statement statement= (Statement) koneksiDB.GetConnection() .createStatement();
            ResultSet res=statement.executeQuery("select * from t_bb");
            while (res.next())
                            
            {
                tbl.addRow(new Object[]{
                    res.getString ("id_BB"),
                    res.getString ("nama_BB"),
                    res.getString ("harga")
            });
                tBB.setModel(tbl);
        }
    }catch (Exception e){
        JOptionPane.showMessageDialog(rootPane, "tabel Bahan Bakar Tidak Ditemukan");
        }
    }
    
    public void datatableBahanBakardipilih(){
        // TODO add your handling code here:
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KMliter;
    private javax.swing.JButton btnHapusBB;
    private javax.swing.JButton btnHapusKen;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnPerbaharuiBB;
    private javax.swing.JButton btnPerbaharuiKen;
    private javax.swing.JButton btnPsiman;
    private javax.swing.JButton btnSimpanBB;
    private javax.swing.JButton btnSimpanKen;
    private javax.swing.JButton btnTambahBB;
    private javax.swing.JButton btnTambahKen;
    private javax.swing.JComboBox<String> comBB;
    private javax.swing.JInternalFrame inFrameBB;
    private javax.swing.JInternalFrame inFrameKendaraan;
    private javax.swing.JInternalFrame inFramePemakaian;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private java.awt.Label label1;
    private javax.swing.JButton lihatGrafik;
    private javax.swing.JList<String> listKendaraan;
    private javax.swing.JTextField pemakaianBB;
    private javax.swing.JTextField pemakaianHargaBB;
    private javax.swing.JTextField pemakaianKMbb;
    private javax.swing.JTable tBB;
    private javax.swing.JTable tKendaraan;
    private javax.swing.JTable tPemakaian;
    private javax.swing.JLabel totalBiaya;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIDbb;
    private javax.swing.JLabel txtJam;
    private javax.swing.JTextField txtJarakT;
    private javax.swing.JTextField txtJenisKen;
    private javax.swing.JTextField txtJenisP;
    private javax.swing.JTextField txtKMakhir;
    private javax.swing.JTextField txtKMawal;
    private javax.swing.JTextField txtNamaBb;
    private javax.swing.JTextField txtNoPlat;
    private javax.swing.JTextField txtNplatP;
    private javax.swing.JTextField txtTahun;
    private javax.swing.JTextField txtTahunP;
    private javax.swing.JLabel txtTanggal;
    // End of variables declaration//GEN-END:variables
}
